/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ims.gui;

import ims.bll.EmployeeBLL;
import ims.dto.Chuyennganh;
import ims.dto.City;
import ims.dto.Dantoc;
import ims.dto.Employees;
import ims.dto.Giadinh;
import ims.dto.Gioitinh;
import ims.dto.Honnhan;
import ims.dto.Khoadaotao;
import ims.dto.Nghenghiep;
import ims.dto.Noidaotao;
import ims.dto.Quoctich;
import ims.dto.Tongiao;
import ims.dto.Trinhdodt;
import ims.dto.Xeploai;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.Date;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javafx.scene.control.ComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NAT
 */
public class Employee extends javax.swing.JFrame implements WindowListener {

    Employees em = new Employees();
    EmployeeBLL bll = new EmployeeBLL();
//    Gioitinh gt = new Gioitinh();
//    City ct = new City();
//    Honnhan hn = new Honnhan();
//    Giadinh gd = new Giadinh();
//    Dantoc dt = new Dantoc();
//    Tongiao tg = new Tongiao();
//    Quoctich qt = new Quoctich();
//    Trinhdodt td = new Trinhdodt();
//    Noidaotao ndt = new Noidaotao();
//    Khoadaotao khoa = new Khoadaotao();
//    Chuyennganh cn = new Chuyennganh();
//    Xeploai xl = new Xeploai();
//    Nghenghiep nn = new Nghenghiep();
//    Employees em;
    String maNV;
    String btName="";
    
    

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        stateButton(true);
        setInfoDialog();
        loadCombo();
        
    }
    
    public Employee (String maNV){
        this.maNV = maNV;
        btName = "Edit";
        initComponents();
        setInfoDialog();
    }

    public void setInfoDialog() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);
        setResizable(false);
    }

    public void stateButton(boolean value) {

//        btNew.setVisible(value);
//        btEdit.setVisible(value);
//        btDelete.setVisible(value);
//        btPrint.setVisible(value);
//        btClose.setVisible(value);
//        btSave.setVisible(!value);
//        btCancel.setVisible(!value);
    }

    
    private void loadCombo() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtManv = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTendem = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtNoisinh = new javax.swing.JTextField();
        txtNguyenquan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtMacc = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cboDate = new datechooser.beans.DateChooserCombo();
        jLabel20 = new javax.swing.JLabel();
        cboSex = new javax.swing.JComboBox<>();
        cboNguyenquan = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCmnd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboNgaycap = new datechooser.beans.DateChooserCombo();
        jLabel3 = new javax.swing.JLabel();
        txtNoicap = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSohochieu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cboNgaycapHC = new datechooser.beans.DateChooserCombo();
        jLabel6 = new javax.swing.JLabel();
        cboNgayhethan = new datechooser.beans.DateChooserCombo();
        jLabel7 = new javax.swing.JLabel();
        txtNoicapHC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboHonnhan = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cboGiadinh = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cboDantoc = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        cboTongiao = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        cboQuoctich = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtTDVH = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cboTDDT = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        cboNoidt = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        cboKhoadt = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        cboChuyennganh = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        txtNamtn = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        cboXeploai = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        cboNghenghiep = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Mã NV");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, 20));

        txtManv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManvActionPerformed(evt);
            }
        });
        jPanel4.add(txtManv, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 13, 229, -1));

        jLabel11.setText("Họ đệm");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel12.setText("Họ và tên");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel13.setText("Nơi sinh");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel14.setText("Nguyên quán");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 132, -1, -1));
        jPanel4.add(txtTendem, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 42, 229, -1));
        jPanel4.add(txtHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 71, 229, -1));
        jPanel4.add(txtNoisinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 100, 620, -1));
        jPanel4.add(txtNguyenquan, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 129, 426, -1));

        jLabel15.setText("Mã chấm công");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 16, -1, -1));
        jPanel4.add(txtMacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 13, 250, -1));

        jLabel17.setText("Tên");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, 20));
        jPanel4.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 42, 250, -1));
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 71, -1, -1));

        jLabel19.setText("Ngày sinh");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, 20));

        cboDate.setWeekStyle(datechooser.view.WeekDaysStyle.FULL);
        cboDate.setLocale(new java.util.Locale("vi", "", ""));
        jPanel4.add(cboDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 71, 140, -1));

        jLabel20.setText("Giới tính");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 40, 20));

        cboSex.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSexItemStateChanged(evt);
            }
        });
        jPanel4.add(cboSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 60, -1));

        cboNguyenquan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNguyenquanItemStateChanged(evt);
            }
        });
        jPanel4.add(cboNguyenquan, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 129, 190, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Số CMND");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel2.add(txtCmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 25, 133, -1));

        jLabel2.setText("Ngày cấp");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 28, -1, -1));

        cboNgaycap.setLocale(new java.util.Locale("vi", "", ""));
        jPanel2.add(cboNgaycap, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 25, 125, -1));

        jLabel3.setText("Nơi cấp");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        jPanel2.add(txtNoicap, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 54, 350, -1));

        jLabel4.setText("Số hộ chiếu");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel2.add(txtSohochieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 83, 131, -1));

        jLabel5.setText("Ngày cấp HC");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        cboNgaycapHC.setLocale(new java.util.Locale("vi", "", ""));
        jPanel2.add(cboNgaycapHC, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 112, 131, -1));

        jLabel6.setText("Ngày hết hạn");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 106, -1, 30));

        cboNgayhethan.setLocale(new java.util.Locale("vi", "", ""));
        jPanel2.add(cboNgayhethan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 124, -1));

        jLabel7.setText("Nơi cấp HC");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel2.add(txtNoicapHC, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 147, 347, -1));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 286, -1, -1));

        jLabel9.setText("TT hôn nhân");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        cboHonnhan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboHonnhanItemStateChanged(evt);
            }
        });
        jPanel2.add(cboHonnhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 176, 347, -1));

        jLabel16.setText("TP gia đình");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        cboGiadinh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboGiadinhItemStateChanged(evt);
            }
        });
        jPanel2.add(cboGiadinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 205, 347, -1));

        jLabel21.setText("Dân tộc");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 234, -1, 20));

        cboDantoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDantocItemStateChanged(evt);
            }
        });
        jPanel2.add(cboDantoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 234, 347, -1));

        jLabel22.setText("Tôn giáo");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 30));

        cboTongiao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTongiaoItemStateChanged(evt);
            }
        });
        jPanel2.add(cboTongiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 263, 347, -1));

        jLabel23.setText("Quốc tịch");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 20));

        cboQuoctich.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboQuoctichItemStateChanged(evt);
            }
        });
        jPanel2.add(cboQuoctich, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 292, 347, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 470, 330));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setText("Trình độ văn hóa");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 28, -1, -1));
        jPanel3.add(txtTDVH, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 25, 276, -1));

        jLabel25.setText("Trình độ đào tạo");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 57, -1, -1));

        cboTDDT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTDDTItemStateChanged(evt);
            }
        });
        jPanel3.add(cboTDDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 54, 276, -1));

        jLabel26.setText("Nơi đào tạo");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        cboNoidt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNoidtItemStateChanged(evt);
            }
        });
        jPanel3.add(cboNoidt, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 83, 276, -1));

        jLabel27.setText("Khoa đào tạo");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        cboKhoadt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboKhoadtItemStateChanged(evt);
            }
        });
        jPanel3.add(cboKhoadt, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 112, 276, -1));

        jLabel28.setText("Chuyên ngành");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        cboChuyennganh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboChuyennganhItemStateChanged(evt);
            }
        });
        jPanel3.add(cboChuyennganh, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 141, 276, -1));

        jLabel29.setText("Năm tốt nghiệp");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel3.add(txtNamtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 170, 270, -1));

        jLabel30.setText("Xếp loại");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        cboXeploai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboXeploaiItemStateChanged(evt);
            }
        });
        jPanel3.add(cboXeploai, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 199, 276, -1));

        jLabel31.setText("Nghề nghiệp");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 234, -1, 20));

        cboNghenghiep.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNghenghiepItemStateChanged(evt);
            }
        });
        jPanel3.add(cboNghenghiep, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 234, 276, -1));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 410, 320));

        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, -1, -1));

        btnClose.setText("Thoát");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel4.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 520, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 120, 140));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 900, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        DefaultComboBoxModel cbDantoc = (DefaultComboBoxModel) cboDantoc.getModel();
        DefaultComboBoxModel cbHonnhan = (DefaultComboBoxModel) cboHonnhan.getModel();
        DefaultComboBoxModel cbGiadinh = (DefaultComboBoxModel) cboGiadinh.getModel();
        DefaultComboBoxModel cbTongiao = (DefaultComboBoxModel) cboTongiao.getModel();
        DefaultComboBoxModel cbQuoctich = (DefaultComboBoxModel) cboQuoctich.getModel();
        DefaultComboBoxModel cbTddt = (DefaultComboBoxModel) cboTDDT.getModel();
        DefaultComboBoxModel cbNdt = (DefaultComboBoxModel) cboNoidt.getModel();
        DefaultComboBoxModel cbKdt = (DefaultComboBoxModel) cboKhoadt.getModel();
        DefaultComboBoxModel cbChuyennganh = (DefaultComboBoxModel) cboChuyennganh.getModel();
        DefaultComboBoxModel cbXeploai = (DefaultComboBoxModel) cboXeploai.getModel();
        DefaultComboBoxModel cbNghenghiep = (DefaultComboBoxModel) cboNghenghiep.getModel();
        DefaultComboBoxModel cbGioitinh = (DefaultComboBoxModel) cboSex.getModel();
        DefaultComboBoxModel cbNguyenquan = (DefaultComboBoxModel) cboNguyenquan.getModel();
//        s


    }//GEN-LAST:event_formWindowOpened

    private void cboSexItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSexItemStateChanged
//        String sex = cboSex.getSelectedItem().toString();
////        bll =  new EmployeeBLL();
//        gt = bll.getGioitinh(sex);
    }//GEN-LAST:event_cboSexItemStateChanged
    
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
//        String birthday = cboDate.getText();
        String manv = txtManv.getText();
//        String macong = txtMacc.getText();
        String ho_tendem = txtTendem.getText();
        String ten = txtTen.getText();
        String hovaten = txtHoten.getText();
//        int gioitinh = Integer.parseInt(cboSex.getSelectedItem().toString());
        //Date ngaysinh = cboDate.getDate();
        
        String noisinh = txtNoisinh.getText();
        String trinhdo = txtTDVH.getText();
//        int namtotnghiep = (Integer) txtNamtn.getValue();
//        String nguyenquan = txtNguyenquan.getText();
//        int cmnd = Integer.parseInt(txtCmnd.getText());
//        String noicap = txtNoicap.getText();
//        String ngaycap = em.getNgaycap();
//        String sohochieu = txtSohochieu.getText();
//        String ngaycaphc = em.getNgaycaphc();
//        String ngayhethanhc = em.getNgayhethanhc();
//        String noicaphc = txtNoicapHC.getText();
        em.setManv(manv);
//        em.setMacc(macong);
        em.setHo_dem(ho_tendem);
        em.setTen(ten);
        em.setHoten(hovaten);
//        em.setNgaycap(ngaycap);
//        em.setNgaysinh(birthday);
//        em.setNgaycaphc(ngaycaphc);
//        em.setNgayhethanhc(ngayhethanhc);
//        em.setGioitinh(gt.getMagt());
//        em.setMahn(hn.getMahn());
//        em.setMatp(ct.getMatp());
//        em.setMadt(dt.getMadt());
//        em.setMatg(tg.getMatg());
//        em.setMaqt(qt.getMaqtich());
//        em.setMatrinhdo(td.getMatd());
//        em.setMaloaitp(gd.getMaloaitp());
//        em.setMadd(ndt.getMadd());
//        em.setMacn(cn.getMacn());
//        em.setMakhoa(khoa.getMakhoa());
//        em.setMaloai(xl.getMaloai());
//        em.setManghe(nn.getManghe());
//        em.setNgaysinh(ngaysinh);
        em.setNoisinh(noisinh);
//        em.setTrinhdo(trinhdo);
//        em.setNamtotnghiep(namtotnghiep);
//        em.setNguyenquan(nguyenquan);
//        em.setCmnd(cmnd);
//        em.setNoicap(noicap);
//        em.setNgaycap(ngaycap);
//        em.setSohochieu(sohochieu);
//        em.setNgaycaphc(ngaycaphc);
//        em.setNgayhethanhc(ngayhethanhc);
//        em.setNoicaphc(noicaphc);
//.        txtHoten.setText(""+em.getMacn());
//        txtTen.setText(""+em.getMatg());
 //       txtTendem.setText(""+em.getNgaysinh());
        bll.addNewEmployee(em);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cboNguyenquanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNguyenquanItemStateChanged
//        txtNguyenquan.setText(cboNguyenquan.getSelectedItem().toString());
//        String city = cboNguyenquan.getSelectedItem().toString();
//        ct = bll.getCity(city);
    }//GEN-LAST:event_cboNguyenquanItemStateChanged

    private void cboHonnhanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboHonnhanItemStateChanged
//        String honnhan = cboHonnhan.getSelectedItem().toString();
//        hn = bll.getTinhtranghn(honnhan);
    }//GEN-LAST:event_cboHonnhanItemStateChanged

    private void cboGiadinhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboGiadinhItemStateChanged
//         String giadinh = cboGiadinh.getSelectedItem().toString();
//         gd = bll.getThanhphangd(giadinh);
    }//GEN-LAST:event_cboGiadinhItemStateChanged

    private void cboDantocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDantocItemStateChanged
//        String dantoc = cboDantoc.getSelectedItem().toString();
//        dt = bll.getDantoc(dantoc);
    }//GEN-LAST:event_cboDantocItemStateChanged

    private void cboTongiaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTongiaoItemStateChanged
//        String tongiao = cboTongiao.getSelectedItem().toString();
//        tg = bll.getTongiao(tongiao);
    }//GEN-LAST:event_cboTongiaoItemStateChanged

    private void cboQuoctichItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboQuoctichItemStateChanged
//        String quoctich = cboQuoctich.getSelectedItem().toString();
//        qt = bll.getQuoctich(quoctich);
    }//GEN-LAST:event_cboQuoctichItemStateChanged

    private void cboTDDTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTDDTItemStateChanged
//        String trinhdo = cboTDDT.getSelectedItem().toString();
//        td = bll.getTrinhdodt(trinhdo);
    }//GEN-LAST:event_cboTDDTItemStateChanged

    private void cboNoidtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNoidtItemStateChanged
//        String noidaotao = cboNoidt.getSelectedItem().toString();
//        ndt = bll.getNoidaotao(noidaotao);
    }//GEN-LAST:event_cboNoidtItemStateChanged

    private void cboKhoadtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboKhoadtItemStateChanged
//        String khoadt = cboKhoadt.getSelectedItem().toString();
//        khoa = bll.getKhoadaotao(khoadt);
    }//GEN-LAST:event_cboKhoadtItemStateChanged

    private void cboChuyennganhItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboChuyennganhItemStateChanged
//        String chuyennganh = cboChuyennganh.getSelectedItem().toString();
//        cn = bll.getChuyennganh(chuyennganh);
    }//GEN-LAST:event_cboChuyennganhItemStateChanged

    private void cboXeploaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboXeploaiItemStateChanged
//        String xeploai = cboXeploai.getSelectedItem().toString();
//        xl = bll.getXeploai(xeploai);
    }//GEN-LAST:event_cboXeploaiItemStateChanged

    private void cboNghenghiepItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNghenghiepItemStateChanged
//        String nghenghiep = cboNghenghiep.getSelectedItem().toString();
//        nn = bll.getNghenghiep(nghenghiep);
    }//GEN-LAST:event_cboNghenghiepItemStateChanged

    private void txtManvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManvActionPerformed
    
    public void loadEmployee(String maNV){
        txtManv.setText(em.getManv());
        txtMacc.setText(em.getMacc());
        txtTendem.setText(em.getHo_dem());
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    public javax.swing.JComboBox<String> cboChuyennganh;
    public javax.swing.JComboBox<String> cboDantoc;
    public datechooser.beans.DateChooserCombo cboDate;
    public javax.swing.JComboBox<String> cboGiadinh;
    public javax.swing.JComboBox<String> cboHonnhan;
    public javax.swing.JComboBox<String> cboKhoadt;
    public datechooser.beans.DateChooserCombo cboNgaycap;
    public datechooser.beans.DateChooserCombo cboNgaycapHC;
    public datechooser.beans.DateChooserCombo cboNgayhethan;
    public javax.swing.JComboBox<String> cboNghenghiep;
    public javax.swing.JComboBox<String> cboNguyenquan;
    public javax.swing.JComboBox<String> cboNoidt;
    public javax.swing.JComboBox<String> cboQuoctich;
    public javax.swing.JComboBox<String> cboSex;
    public javax.swing.JComboBox<String> cboTDDT;
    public javax.swing.JComboBox<String> cboTongiao;
    public javax.swing.JComboBox<String> cboXeploai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JTextField txtCmnd;
    public javax.swing.JTextField txtHoten;
    public javax.swing.JTextField txtMacc;
    public javax.swing.JTextField txtManv;
    public javax.swing.JSpinner txtNamtn;
    public javax.swing.JTextField txtNguyenquan;
    public javax.swing.JTextField txtNoicap;
    public javax.swing.JTextField txtNoicapHC;
    public javax.swing.JTextField txtNoisinh;
    public javax.swing.JTextField txtSohochieu;
    public javax.swing.JTextField txtTDVH;
    public javax.swing.JTextField txtTen;
    public javax.swing.JTextField txtTendem;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosing(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowClosed(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowIconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowActivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
